AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Stack for EMR on EKS clusters"

Metadata:
  cfn-lint:
    config:
      ignore_checks:
       - W2001

Parameters:
  ProjectName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: "SHS-EMROnEKSStack"

  VPC:
    Description: The VPC ID where EKS clusters will be created
    Type: AWS::EC2::VPC::Id

  PrivateSubnets:
    Description: List of private subnet IDs for EKS clusters
    Type: List<AWS::EC2::Subnet::Id>

  InstanceType:
    Description: EC2 instance type for EKS node groups
    Type: String
    Default: m5.2xlarge

  DataScienceClusterName:
    Description: Name of the Data Science EKS cluster
    Type: String
    Default: datascience-cluster

  AnalyticsClusterName:
    Description: Name of the Analytics EKS cluster
    Type: String
    Default: analytics-cluster

  ClusterVersion:
    Description: Kubernetes version for EKS clusters
    Type: String
    Default: "1.32"

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Metadata:
      cdk_nag:
        rules_to_suppress:
          - id: AwsSolutions-IAM4
            reason: "AmazonEKSClusterPolicy is required for EKS cluster functionality"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSNodeRole:
    Type: AWS::IAM::Role
    Metadata:
      cdk_nag:
        rules_to_suppress:
          - id: AwsSolutions-IAM4
            reason: "Required AWS managed policies for EKS worker nodes functionality"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  EKSKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for EKS cluster secrets encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow EKS to use the key
            Effect: Allow
            Principal:
              AWS: !GetAtt EKSClusterRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  ######### Data Science EKS Cluster #########
  DataScienceEKSCluster:
    Type: AWS::EKS::Cluster
    Metadata:
      cdk_nag:
        rules_to_suppress:
          - id: AwsSolutions-EKS1
            reason: "Public access is disabled in the blog post configuration"
          - id: AwsSolutions-EKS2
            reason: "Control plane logging is not required for this blog post demonstration"
    Properties:
      Name: !Ref DataScienceClusterName
      Version: !Ref ClusterVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref PrivateSubnets
        SecurityGroupIds: []
      EncryptionConfig:
        - Provider:
            KeyArn: !GetAtt EKSKMSKey.Arn
          Resources:
            - secrets
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName

  DataScienceNodeGroup:
    Type: AWS::EKS::Nodegroup
    DeletionPolicy: Delete
    UpdatePolicy:
      UpdateReplacePolicy: Retain
    Properties:
      ClusterName: !Ref DataScienceEKSCluster
      NodeRole: !GetAtt EKSNodeRole.Arn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 5
      InstanceTypes:
        - !Ref InstanceType
      Subnets: !Ref PrivateSubnets

  ######### Analytics EKS Cluster #########
  AnalyticsEKSCluster:
    Type: AWS::EKS::Cluster
    Metadata:
      cdk_nag:
        rules_to_suppress:
          - id: AwsSolutions-EKS1
            reason: "Public access is disabled in the blog post configuration"
          - id: AwsSolutions-EKS2
            reason: "Control plane logging is not required for this blog post demonstration"
    Properties:
      Name: !Ref AnalyticsClusterName
      Version: !Ref ClusterVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref PrivateSubnets
        SecurityGroupIds: []
      EncryptionConfig:
        - Provider:
            KeyArn: !GetAtt EKSKMSKey.Arn
          Resources:
            - secrets
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName

  AnalyticsNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref AnalyticsEKSCluster
      NodeRole: !GetAtt EKSNodeRole.Arn
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 5
      InstanceTypes:
        - !Ref InstanceType
      Subnets: !Ref PrivateSubnets

Outputs:
  DataScienceClusterName:
    Description: Name of the Data Science EKS cluster
    Value: !Ref DataScienceEKSCluster

  AnalyticsClusterName:
    Description: Name of the Analytics EKS cluster
    Value: !Ref AnalyticsEKSCluster

  DataScienceClusterEndpoint:
    Description: Endpoint for the Data Science EKS cluster
    Value: !GetAtt DataScienceEKSCluster.Endpoint

  AnalyticsClusterEndpoint:
    Description: Endpoint for the Analytics EKS cluster
    Value: !GetAtt AnalyticsEKSCluster.Endpoint

  EKSSecurityGroups:
    Description: Security Groups for the EKS clusters
    Value:
      !Join [
        ",",
        [
          !GetAtt DataScienceEKSCluster.ClusterSecurityGroupId,
          !GetAtt AnalyticsEKSCluster.ClusterSecurityGroupId
        ],
      ]

  DataScienceEKSSecurityGroup:
    Description: ID of the first EKS Security Group
    Value: !GetAtt DataScienceEKSCluster.ClusterSecurityGroupId

  AnalyticsEKSSecurityGroup:
    Description: ID of the second EKS Security Group
    Value: !GetAtt AnalyticsEKSCluster.ClusterSecurityGroupId

  DataScienceClusterOidcProviderUrl:
    Value:
      !Select [
        1,
        !Split [
          "https://",
          !GetAtt DataScienceEKSCluster.OpenIdConnectIssuerUrl,
        ],
      ]

  AnalyticsClusterOidcProviderUrl:
    Value:
      !Select [
        1,
        !Split ["https://", !GetAtt AnalyticsEKSCluster.OpenIdConnectIssuerUrl],
      ]
